// CaseLens — stylesheet
//
// Split out of the core file because it is 1,378 lines of CSS with no logic in
// it, and its bulk made the ~1,100 lines an auditor actually needs to read —
// the endpoints, the storage, the fetch layer — harder to find rather than
// easier. Concatenated ahead of the core by scripts/build.js; the file people
// install is still one file, and `node scripts/build.js --check` proves it.
//
// Every rule is scoped under .uscistr-root. Light and dark are both defined
// here; dark is the single class .uscistr-dark on that root.

var CASELENS_STYLE = [
  ".uscistr-root {",
  "  all: initial;",
  "  --ust-font: -apple-system, BlinkMacSystemFont, \"Segoe UI Variable Text\", \"Segoe UI\", system-ui, Roboto, \"Helvetica Neue\", Arial, sans-serif;",
  "  --ust-mono: ui-monospace, SFMono-Regular, \"SF Mono\", \"Cascadia Mono\", \"Segoe UI Mono\", Menlo, Consolas, \"Liberation Mono\", monospace;",
  // A serif for the status headline and card titles. This is the single
  // strongest signal that the panel is a record rather than a dashboard —
  // notices, letters and case files are set in serif, product chrome is not.
  // All faces below ship with the OS; nothing is fetched.
  "  --ust-serif: \"Iowan Old Style\", \"Palatino Linotype\", Palatino, \"Book Antiqua\", Georgia, \"Times New Roman\", serif;",
  "  --ust-fs-title: 13px;      --ust-lh-title: 1.25;",
  "  --ust-fs-heading: 13.5px;  --ust-lh-heading: 1.35;",
  "  --ust-fs-body: 12.5px;     --ust-lh-body: 1.55;",
  "  --ust-fs-meta: 11.5px;     --ust-lh-meta: 1.45;",
  "  --ust-fs-label: 10.5px;    --ust-lh-label: 1.2;",
  "  --ust-fs-mono: 12px;       --ust-lh-mono: 1.4;",
  "  --ust-fs-micro: 10.5px;    --ust-lh-micro: 1.35;",
  "  --ust-s1: 2px;  --ust-s2: 4px;  --ust-s3: 6px;  --ust-s4: 8px;  --ust-s5: 10px;",
  "  --ust-s6: 12px; --ust-s7: 16px; --ust-s8: 20px; --ust-s9: 24px; --ust-s10: 32px;",
  "  --ust-r-xs: 4px; --ust-r-sm: 6px; --ust-r-md: 8px;",
  "  --ust-r-lg: 8px; --ust-r-xl: 10px; --ust-r-full: 999px;",
  "  --ust-bg-panel: #FFFFFF;",
  "  --ust-bg-raised: rgba(255, 255, 255, 0.84);",
  "  --ust-bg-raised-solid: #FFFFFF;",
  "  --ust-bg-sunken: #F7F5F0;",
  "  --ust-bg-inset: #F1EEE7;",
  "  --ust-bg-hover: rgba(16, 19, 24, 0.045);",
  "  --ust-bg-active: rgba(16, 19, 24, 0.085);",
  "  --ust-tint-accent: rgba(79, 70, 229, 0.045);",
  "  --ust-text-1: #101318;",
  "  --ust-text-2: #3F4756;",
  "  --ust-text-3: #5F6776;",
  "  --ust-text-inv: #FFFFFF;",
  "  --ust-border-1: #E8EAEE;",
  "  --ust-border-2: #D8DCE3;",
  "  --ust-border-field: #868E9F;",
  "  --ust-accent: #1F5D5B;",
  "  --ust-accent-solid: #1F5D5B;",
  "  --ust-accent-solid-hover: #194B49;",
  "  --ust-accent-solid-active: #133A39;",
  "  --ust-accent-on: #FFFFFF;",
  "  --ust-accent-soft: #E7F0EE;",
  "  --ust-accent-soft-text: #174A48;",
  "  --ust-accent-soft-border: #C6DBD7;",
  "  --ust-success: #067647; --ust-success-soft: #E6F6EE; --ust-success-text: #05603A; --ust-success-border: #B3E2CB;",
  "  --ust-warn:    #B54708; --ust-warn-soft:    #FDF3E4; --ust-warn-text:    #93370D; --ust-warn-border:    #F0D9AE;",
  "  --ust-danger:  #B42318; --ust-danger-soft:  #FEEDEB; --ust-danger-text:  #912018; --ust-danger-border:  #F6CCC6;",
  "  --ust-info:    #175CD3; --ust-info-soft:    #EAF1FE; --ust-info-text:    #0B4A9E; --ust-info-border:    #C3D8F8;",
  "  --ust-track: #E7E9EF;",
  "  --ust-scroll-thumb: #C9CED8;",
  "  --ust-scroll-thumb-hover: #AEB5C2;",
  "  --ust-focus: #4F46E5;",
  "  --ust-focus-halo: rgba(79, 70, 229, 0.30);",
  "  --ust-sh-1: 0 1px 2px rgba(16, 24, 40, 0.06), 0 1px 1px rgba(16, 24, 40, 0.04);",
  "  --ust-sh-2: 0 2px 4px -1px rgba(16, 24, 40, 0.07), 0 4px 10px -2px rgba(16, 24, 40, 0.08);",
  "  --ust-sh-3: 0 1px 2px rgba(16, 24, 40, 0.06), 0 8px 16px -6px rgba(16, 24, 40, 0.12), 0 24px 48px -16px rgba(16, 24, 40, 0.20);",
  "  --ust-sh-pop: 0 2px 6px rgba(16, 24, 40, 0.08), 0 14px 30px -10px rgba(16, 24, 40, 0.22);",
  "  --ust-sh-inner: none;",
  "  --ust-d1: 90ms;  --ust-d2: 150ms; --ust-d3: 220ms; --ust-d4: 320ms;",
  "  --ust-ease: cubic-bezier(0.2, 0, 0, 1);",
  "  --ust-ease-out: cubic-bezier(0.05, 0.7, 0.1, 1);",
  "  --ust-ease-in: cubic-bezier(0.3, 0, 0.8, 0.15);",
  "  --ust-ease-spring: cubic-bezier(0.34, 1.4, 0.64, 1);",
  "  color-scheme: light;",
  "  direction: ltr;",
  "  display: block;",
  "  position: fixed;",
  "  top: 0;",
  "  left: 0;",
  "  width: 0;",
  "  height: 0;",
  "  overflow: visible;",
  "  z-index: 2147483647;",
  "  pointer-events: none;",
  "  isolation: isolate;",
  "  font-family: var(--ust-font);",
  "  font-size: var(--ust-fs-body);",
  "  line-height: var(--ust-lh-body);",
  "  font-weight: 400;",
  "  color: var(--ust-text-1);",
  "  text-align: left;",
  "  -webkit-font-smoothing: antialiased;",
  "  -moz-osx-font-smoothing: grayscale;",
  "  text-rendering: optimizeLegibility;",
  "  font-variant-ligatures: none;",
  "}",
  ".uscistr-root.uscistr-dark {",
  "  color-scheme: dark;",
  "  --ust-bg-panel: #191A1F;",
  "  --ust-bg-raised: rgba(29, 30, 36, 0.84);",
  "  --ust-bg-raised-solid: #1D1E24;",
  "  --ust-bg-sunken: #131418;",
  "  --ust-bg-inset: #212329;",
  "  --ust-bg-hover: rgba(255, 255, 255, 0.055);",
  "  --ust-bg-active: rgba(255, 255, 255, 0.10);",
  "  --ust-tint-accent: rgba(139, 136, 247, 0.075);",
  "  --ust-text-1: #EBECF0;",
  "  --ust-text-2: #ADB2BF;",
  "  --ust-text-3: #8B92A1;",
  "  --ust-text-inv: #FFFFFF;",
  "  --ust-border-1: #2A2D35;",
  "  --ust-border-2: #3A3E49;",
  "  --ust-border-field: #666D7D;",
  "  --ust-accent: #7FC9C2;",
  "  --ust-accent-solid: #2C7A75;",
  "  --ust-accent-solid-hover: #359089;",
  "  --ust-accent-solid-active: #24635F;",
  "  --ust-accent-on: #FFFFFF;",
  "  --ust-accent-soft: #142B2A;",
  "  --ust-accent-soft-text: #9BD8D1;",
  "  --ust-accent-soft-border: #24504C;",
  "  --ust-success: #5FD3A0; --ust-success-soft: #14241E; --ust-success-text: #7FE3B5; --ust-success-border: #21493A;",
  "  --ust-warn:    #F5B860; --ust-warn-soft:    #26200F; --ust-warn-text:    #FAC97E; --ust-warn-border:    #4A3A18;",
  "  --ust-danger:  #FF9A90; --ust-danger-soft:  #271817; --ust-danger-text:  #FFA79E; --ust-danger-border:  #4E2A27;",
  "  --ust-info:    #8FBBF7; --ust-info-soft:    #141F2E; --ust-info-text:    #9CC4F8; --ust-info-border:    #23405E;",
  "  --ust-track: #2A2D35;",
  "  --ust-scroll-thumb: #3E434F;",
  "  --ust-scroll-thumb-hover: #545B6A;",
  "  --ust-focus: #8B88F7;",
  "  --ust-focus-halo: rgba(139, 136, 247, 0.34);",
  "  --ust-sh-1: 0 1px 2px rgba(0, 0, 0, 0.45);",
  "  --ust-sh-2: 0 2px 6px rgba(0, 0, 0, 0.5);",
  "  --ust-sh-3: 0 0 0 1px rgba(0, 0, 0, 0.55), 0 12px 28px -8px rgba(0, 0, 0, 0.7), 0 32px 64px -24px rgba(0, 0, 0, 0.65);",
  "  --ust-sh-pop: 0 0 0 1px rgba(0, 0, 0, 0.5), 0 14px 30px -10px rgba(0, 0, 0, 0.7);",
  "  --ust-sh-inner: inset 0 1px 0 rgba(255, 255, 255, 0.055);",
  "}",
  ".uscistr-root *,",
  ".uscistr-root *::before,",
  ".uscistr-root *::after {",
  "  box-sizing: border-box;",
  "  margin: 0;",
  "  padding: 0;",
  "  border: 0 solid transparent;",
  "  border-radius: 0;",
  "  background: none;",
  "  background-color: transparent;",
  "  font: inherit;",
  "  font-family: inherit;",
  "  font-size: inherit;",
  "  font-weight: inherit;",
  "  font-style: normal;",
  "  font-variant: normal;",
  "  line-height: inherit;",
  "  color: inherit;",
  "  letter-spacing: normal;",
  "  word-spacing: normal;",
  "  text-align: inherit;",
  "  text-decoration: none;",
  "  text-indent: 0;",
  "  text-shadow: none;",
  "  text-transform: none;",
  "  white-space: normal;",
  "  vertical-align: baseline;",
  "  list-style: none;",
  "  float: none;",
  "  clear: none;",
  "  position: static;",
  "  inset: auto;",
  "  box-shadow: none;",
  "  outline: none;",
  "  opacity: 1;",
  "  visibility: visible;",
  "  transform: none;",
  "  filter: none;",
  "  animation: none;",
  "  transition: none;",
  "  mix-blend-mode: normal;",
  "  clip-path: none;",
  "  pointer-events: auto;",
  "  cursor: inherit;",
  "  -webkit-appearance: none;",
  "  appearance: none;",
  "  -webkit-tap-highlight-color: transparent;",
  "}",
  ".uscistr-root *:not(svg):not(svg *),",
  ".uscistr-root *::before,",
  ".uscistr-root *::after {",
  "  width: auto;",
  "  height: auto;",
  "  min-width: 0;",
  "  min-height: 0;",
  "  max-width: none;",
  "  max-height: none;",
  "}",
  ".uscistr-root svg { display: block; overflow: visible; }",
  ".uscistr-root svg * { fill: none; stroke: none; }",
  ".uscistr-root .uscistr-ico {",
  "  display: block;",
  "  fill: none;",
  "  stroke: currentColor;",
  "  stroke-width: 1.6;",
  "  stroke-linecap: round;",
  "  stroke-linejoin: round;",
  "}",
  ".uscistr-root .uscistr-ico * { fill: none; stroke: currentColor; }",
  ".uscistr-root :focus { outline: none; }",
  ".uscistr-root .uscistr-focusable:focus-visible,",
  ".uscistr-root .uscistr-btn:focus-visible,",
  ".uscistr-root .uscistr-icon-btn:focus-visible,",
  ".uscistr-root .uscistr-input:focus-visible,",
  ".uscistr-root .uscistr-select:focus-visible,",
  ".uscistr-root .uscistr-switch:focus-visible,",
  ".uscistr-root .uscistr-pill:focus-visible,",
  ".uscistr-root .uscistr-raw-summary:focus-visible,",
  ".uscistr-root .uscistr-receipt:focus-visible,",
  ".uscistr-root .uscistr-link:focus-visible {",
  "  outline: 2px solid var(--ust-focus);",
  "  outline-offset: 2px;",
  "  box-shadow: 0 0 0 4px var(--ust-focus-halo);",
  "}",
  "@media (forced-colors: active) {",
  "  .uscistr-root .uscistr-panel,",
  "  .uscistr-root .uscistr-pill,",
  "  .uscistr-root .uscistr-card,",
  "  .uscistr-root .uscistr-chip { border: 1px solid CanvasText; }",
  "  .uscistr-root .uscistr-btn:focus-visible,",
  "  .uscistr-root .uscistr-icon-btn:focus-visible { outline: 3px solid Highlight; }",
  "}",
  ".uscistr-root .uscistr-pill {",
  "  position: fixed;",
  "  right: 20px;",
  "  bottom: 20px;",
  "  pointer-events: auto;",
  "  display: inline-flex;",
  "  align-items: center;",
  "  gap: var(--ust-s3);",
  "  height: 36px;",
  "  padding: 0 var(--ust-s5) 0 var(--ust-s4);",
  "  border: 1px solid var(--ust-border-2);",
  "  border-radius: var(--ust-r-full);",
  "  background: var(--ust-bg-panel);",
  "  color: var(--ust-text-1);",
  "  font-family: var(--ust-font);",
  "  font-size: var(--ust-fs-title);",
  "  font-weight: 560;",
  "  line-height: 1;",
  "  letter-spacing: -0.005em;",
  "  box-shadow: var(--ust-sh-2), var(--ust-sh-inner);",
  "  cursor: pointer;",
  "  transition: transform var(--ust-d1) var(--ust-ease),",
  "              box-shadow var(--ust-d2) var(--ust-ease),",
  "              background-color var(--ust-d1) var(--ust-ease),",
  "              border-color var(--ust-d1) var(--ust-ease);",
  "}",
  ".uscistr-root .uscistr-pill:hover {",
  "  background: var(--ust-bg-panel);",
  "  border-color: var(--ust-border-field);",
  "  box-shadow: var(--ust-sh-3), var(--ust-sh-inner);",
  "  transform: translateY(-1px);",
  "}",
  ".uscistr-root .uscistr-pill:active { transform: translateY(0) scale(0.985); box-shadow: var(--ust-sh-1); }",
  ".uscistr-root .uscistr-pill-label { white-space: nowrap; }",
  ".uscistr-root .uscistr-pill-count {",
  "  display: inline-flex;",
  "  align-items: center;",
  "  justify-content: center;",
  "  min-width: 18px;",
  "  height: 18px;",
  "  padding: 0 5px;",
  "  border-radius: var(--ust-r-full);",
  "  background: var(--ust-bg-inset);",
  "  color: var(--ust-text-2);",
  "  font-family: var(--ust-mono);",
  "  font-size: 10.5px;",
  "  font-weight: 600;",
  "  font-variant-numeric: tabular-nums;",
  "  line-height: 1;",
  "}",
  ".uscistr-root .uscistr-pill-dot {",
  "  position: relative;",
  "  width: 7px;",
  "  height: 7px;",
  "  border-radius: var(--ust-r-full);",
  "  background: var(--ust-accent-solid);",
  "  flex: none;",
  "}",
  ".uscistr-root .uscistr-pill-dot::after {",
  "  content: \"\";",
  "  position: absolute;",
  "  inset: -3px;",
  "  border-radius: var(--ust-r-full);",
  "  border: 1px solid var(--ust-accent-solid);",
  "  opacity: 0;",
  "  animation: ust-ping 2.4s var(--ust-ease-out) infinite;",
  "}",
  ".uscistr-root .uscistr-pill-mark { width: 18px; height: 18px; flex: none; }",
  ".uscistr-root .uscistr-panel {",
  "  position: fixed;",
  "  right: 20px;",
  "  bottom: 20px;",
  "  pointer-events: auto;",
  "  display: flex;",
  "  flex-direction: column;",
  "  width: 400px;",
  "  max-width: calc(100vw - 24px);",
  "  max-height: 85vh;",
  "  border: 1px solid var(--ust-border-2);",
  "  border-radius: var(--ust-r-xl);",
  "  background: var(--ust-bg-panel);",
  "  color: var(--ust-text-1);",
  "  box-shadow: var(--ust-sh-3);",
  "  overflow: hidden;",
  "  animation: ust-panel-in var(--ust-d4) var(--ust-ease-out) both;",
  "}",
  ".uscistr-root .uscistr-panel.uscistr-is-dragging {",
  "  box-shadow: var(--ust-sh-3), 0 0 0 1px var(--ust-accent-soft-border);",
  "  cursor: grabbing;",
  "  user-select: none;",
  "}",
  ".uscistr-root .uscistr-header {",
  "  position: sticky;",
  "  top: 0;",
  "  z-index: 3;",
  "  flex: none;",
  "  display: grid;",
  "  grid-template-columns: auto 1fr auto;",
  "  align-items: center;",
  "  gap: var(--ust-s4);",
  "  height: 46px;",
  "  padding: 0 var(--ust-s3) 0 var(--ust-s6);",
  "  background: var(--ust-bg-raised);",
  "  -webkit-backdrop-filter: blur(14px) saturate(180%);",
  "  backdrop-filter: blur(14px) saturate(180%);",
  "  box-shadow: inset 0 -1px 0 var(--ust-border-1);",
  "  cursor: grab;",
  "  user-select: none;",
  "}",
  ".uscistr-root .uscistr-header:active { cursor: grabbing; }",
  ".uscistr-root .uscistr-brand { display: flex; align-items: center; gap: var(--ust-s3); min-width: 0; }",
  ".uscistr-root .uscistr-brand-name { font-family: var(--ust-serif); font-size: 15px; letter-spacing: 0.005em; }",
  ".uscistr-root .uscistr-mark {",
  "  width: 22px; height: 22px; flex: none;",
  "  border-radius: var(--ust-r-sm);",
  "  box-shadow: var(--ust-sh-1);",
  "}",
  ".uscistr-root .uscistr-titles { display: flex; flex-direction: column; gap: 1px; min-width: 0; }",
  ".uscistr-root .uscistr-title {",
  "  font-size: var(--ust-fs-title);",
  "  line-height: var(--ust-lh-title);",
  "  font-weight: 600;",
  "  letter-spacing: -0.008em;",
  "  color: var(--ust-text-1);",
  "  white-space: nowrap;",
  "  overflow: hidden;",
  "  text-overflow: ellipsis;",
  "}",
  ".uscistr-root .uscistr-subtitle {",
  "  font-size: 10.5px;",
  "  line-height: 1.2;",
  "  color: var(--ust-text-3);",
  "  font-variant-numeric: tabular-nums;",
  "  white-space: nowrap;",
  "}",
  ".uscistr-root .uscistr-header-actions { display: flex; align-items: center; gap: var(--ust-s1); }",
  ".uscistr-root .uscistr-body {",
  "  flex: 1 1 auto;",
  "  min-height: 0;",
  "  overflow-y: auto;",
  "  overflow-x: hidden;",
  "  overscroll-behavior: contain;",
  "  scrollbar-width: thin;",
  "  scrollbar-color: var(--ust-scroll-thumb) transparent;",
  "}",
  ".uscistr-root .uscistr-body::-webkit-scrollbar { width: 11px; height: 11px; }",
  ".uscistr-root .uscistr-body::-webkit-scrollbar-track { background: transparent; }",
  ".uscistr-root .uscistr-body::-webkit-scrollbar-thumb {",
  "  background-color: var(--ust-scroll-thumb);",
  "  border: 3px solid transparent;",
  "  background-clip: padding-box;",
  "  border-radius: var(--ust-r-full);",
  "}",
  ".uscistr-root .uscistr-body::-webkit-scrollbar-thumb:hover { background-color: var(--ust-scroll-thumb-hover); }",
  ".uscistr-root .uscistr-footer {",
  "  flex: none;",
  "  display: flex;",
  "  align-items: center;",
  "  justify-content: space-between;",
  "  gap: var(--ust-s4);",
  "  height: 34px;",
  "  padding: 0 var(--ust-s6);",
  "  background: var(--ust-bg-raised);",
  "  -webkit-backdrop-filter: blur(14px) saturate(180%);",
  "  backdrop-filter: blur(14px) saturate(180%);",
  "  box-shadow: inset 0 1px 0 var(--ust-border-1);",
  "  font-size: 10.5px;",
  "  line-height: 1.2;",
  "  color: var(--ust-text-3);",
  "  font-variant-numeric: tabular-nums;",
  "}",
  ".uscistr-root .uscistr-footer-left,",
  ".uscistr-root .uscistr-footer-right { display: flex; align-items: center; gap: var(--ust-s3); min-width: 0; }",
  ".uscistr-root .uscistr-footer-sep { color: var(--ust-border-2); }",
  ".uscistr-root .uscistr-footer svg { width: 12px; height: 12px; color: var(--ust-text-3); }",
  ".uscistr-root .uscistr-btn {",
  "  display: inline-flex;",
  "  align-items: center;",
  "  justify-content: center;",
  "  gap: var(--ust-s3);",
  "  height: 28px;",
  "  padding: 0 var(--ust-s5);",
  "  border: 1px solid transparent;",
  "  border-radius: var(--ust-r-md);",
  "  background: transparent;",
  "  color: var(--ust-text-2);",
  "  font-family: var(--ust-font);",
  "  font-size: 12px;",
  "  font-weight: 560;",
  "  line-height: 1;",
  "  letter-spacing: -0.003em;",
  "  white-space: nowrap;",
  "  cursor: pointer;",
  "  transition: background-color var(--ust-d1) var(--ust-ease),",
  "              color var(--ust-d1) var(--ust-ease),",
  "              border-color var(--ust-d1) var(--ust-ease),",
  "              box-shadow var(--ust-d1) var(--ust-ease),",
  "              transform var(--ust-d1) var(--ust-ease);",
  "}",
  ".uscistr-root .uscistr-btn svg { width: 14px; height: 14px; flex: none; }",
  ".uscistr-root .uscistr-btn:active { transform: translateY(0.5px); }",
  ".uscistr-root .uscistr-btn:disabled,",
  ".uscistr-root .uscistr-btn[aria-disabled=\"true\"] {",
  "  opacity: 0.42;",
  "  cursor: not-allowed;",
  "  transform: none;",
  "  pointer-events: none;",
  "}",
  ".uscistr-root .uscistr-btn-sm { height: 24px; padding: 0 var(--ust-s4); font-size: 11.5px; border-radius: var(--ust-r-sm); }",
  ".uscistr-root .uscistr-btn-sm svg { width: 12px; height: 12px; }",
  ".uscistr-root .uscistr-btn-primary {",
  "  background: var(--ust-accent-solid);",
  "  border-color: transparent;",
  "  color: var(--ust-accent-on);",
  "  box-shadow: var(--ust-sh-1);",
  "  font-weight: 600;",
  "}",
  ".uscistr-root .uscistr-btn-primary:hover { background: var(--ust-accent-solid-hover); box-shadow: var(--ust-sh-2); }",
  ".uscistr-root .uscistr-btn-primary:active { background: var(--ust-accent-solid-active); box-shadow: none; }",
  ".uscistr-root .uscistr-btn-outline {",
  "  background: var(--ust-bg-panel);",
  "  border-color: var(--ust-border-2);",
  "  color: var(--ust-text-1);",
  "  box-shadow: var(--ust-sh-1);",
  "}",
  ".uscistr-root .uscistr-btn-outline:hover { background: var(--ust-bg-sunken); border-color: var(--ust-border-field); }",
  ".uscistr-root .uscistr-btn-outline:active { background: var(--ust-bg-inset); box-shadow: none; }",
  ".uscistr-root .uscistr-btn-ghost { background: transparent; border-color: transparent; color: var(--ust-text-2); }",
  ".uscistr-root .uscistr-btn-ghost:hover { background: var(--ust-bg-hover); color: var(--ust-text-1); }",
  ".uscistr-root .uscistr-btn-ghost:active { background: var(--ust-bg-active); }",
  ".uscistr-root .uscistr-btn-danger {",
  "  background: transparent;",
  "  border-color: transparent;",
  "  color: var(--ust-danger-text);",
  "}",
  ".uscistr-root .uscistr-btn-danger:hover { background: var(--ust-danger-soft); border-color: var(--ust-danger-border); }",
  ".uscistr-root .uscistr-btn-danger:active { background: var(--ust-danger); border-color: transparent; color: #FFFFFF; }",
  ".uscistr-root.uscistr-dark .uscistr-btn-danger:active { color: #1A0F0E; }",
  ".uscistr-root .uscistr-icon-btn {",
  "  display: inline-flex;",
  "  align-items: center;",
  "  justify-content: center;",
  "  width: 28px;",
  "  height: 28px;",
  "  border: 1px solid transparent;",
  "  border-radius: var(--ust-r-md);",
  "  background: transparent;",
  "  color: var(--ust-text-3);",
  "  cursor: pointer;",
  "  transition: background-color var(--ust-d1) var(--ust-ease), color var(--ust-d1) var(--ust-ease);",
  "}",
  ".uscistr-root .uscistr-icon-btn svg { width: 15px; height: 15px; }",
  ".uscistr-root .uscistr-icon-btn:hover { background: var(--ust-bg-hover); color: var(--ust-text-1); }",
  ".uscistr-root .uscistr-icon-btn:active { background: var(--ust-bg-active); }",
  ".uscistr-root .uscistr-icon-btn.uscistr-is-on { background: var(--ust-accent-soft); color: var(--ust-accent-soft-text); }",
  ".uscistr-root .uscistr-icon-btn:disabled { opacity: 0.4; cursor: not-allowed; pointer-events: none; }",
  ".uscistr-root .uscistr-icon-btn.uscistr-is-busy svg { animation: ust-spin 900ms linear infinite; }",
  ".uscistr-root .uscistr-input,",
  ".uscistr-root .uscistr-select {",
  "  display: block;",
  "  width: 100%;",
  "  height: 30px;",
  "  padding: 0 var(--ust-s4);",
  "  border: 1px solid var(--ust-border-field);",
  "  border-radius: var(--ust-r-md);",
  "  background: var(--ust-bg-panel);",
  "  color: var(--ust-text-1);",
  "  font-family: var(--ust-font);",
  "  font-size: 12.5px;",
  "  line-height: 28px;",
  "  transition: border-color var(--ust-d1) var(--ust-ease), box-shadow var(--ust-d1) var(--ust-ease), background-color var(--ust-d1) var(--ust-ease);",
  "}",
  ".uscistr-root .uscistr-input::placeholder { color: var(--ust-text-3); opacity: 1; }",
  ".uscistr-root .uscistr-input:hover,",
  ".uscistr-root .uscistr-select:hover { border-color: var(--ust-text-3); }",
  ".uscistr-root .uscistr-input:focus-visible,",
  ".uscistr-root .uscistr-select:focus-visible { border-color: var(--ust-accent); outline-offset: 1px; }",
  ".uscistr-root .uscistr-input:disabled { background: var(--ust-bg-inset); color: var(--ust-text-3); cursor: not-allowed; }",
  ".uscistr-root .uscistr-input.uscistr-is-invalid { border-color: var(--ust-danger); }",
  ".uscistr-root .uscistr-input.uscistr-mono { font-family: var(--ust-mono); font-size: 12px; letter-spacing: 0.04em; text-transform: uppercase; }",
  ".uscistr-root .uscistr-select {",
  "  padding-right: 26px;",
  "  background-image: linear-gradient(45deg, transparent 50%, currentColor 50%), linear-gradient(135deg, currentColor 50%, transparent 50%);",
  "  background-position: calc(100% - 14px) 13px, calc(100% - 9px) 13px;",
  "  background-size: 5px 5px, 5px 5px;",
  "  background-repeat: no-repeat;",
  "  cursor: pointer;",
  "}",
  ".uscistr-root .uscistr-field { display: flex; flex-direction: column; gap: var(--ust-s2); min-width: 0; }",
  ".uscistr-root .uscistr-field-error { font-size: var(--ust-fs-micro); line-height: 1.4; color: var(--ust-danger-text); }",
  ".uscistr-root .uscistr-add-form {",
  "  display: grid;",
  "  grid-template-columns: 1.15fr 1fr auto;",
  "  gap: var(--ust-s3);",
  "  align-items: center;",
  "  padding: var(--ust-s5) var(--ust-s6);",
  "  background: var(--ust-bg-sunken);",
  "  box-shadow: inset 0 -1px 0 var(--ust-border-1);",
  "}",
  ".uscistr-root .uscistr-switch {",
  "  position: relative;",
  "  flex: none;",
  "  width: 32px;",
  "  height: 19px;",
  "  border: 1px solid var(--ust-border-field);",
  "  border-radius: var(--ust-r-full);",
  "  background: var(--ust-bg-inset);",
  "  cursor: pointer;",
  "  transition: background-color var(--ust-d2) var(--ust-ease), border-color var(--ust-d2) var(--ust-ease);",
  "}",
  ".uscistr-root .uscistr-switch::after {",
  "  content: \"\";",
  "  position: absolute;",
  "  top: 2px;",
  "  left: 2px;",
  "  width: 13px;",
  "  height: 13px;",
  "  border-radius: var(--ust-r-full);",
  "  background: var(--ust-bg-panel);",
  "  box-shadow: 0 1px 2px rgba(16, 24, 40, 0.35);",
  "  transition: transform var(--ust-d2) var(--ust-ease-spring);",
  "}",
  ".uscistr-root .uscistr-switch[aria-checked=\"true\"] { background: var(--ust-accent-solid); border-color: var(--ust-accent-solid); }",
  ".uscistr-root .uscistr-switch[aria-checked=\"true\"]::after { transform: translateX(13px); background: #FFFFFF; }",
  ".uscistr-root .uscistr-switch:disabled { opacity: 0.45; cursor: not-allowed; }",
  ".uscistr-root .uscistr-chip {",
  "  display: inline-flex;",
  "  align-items: center;",
  "  gap: var(--ust-s2);",
  "  height: 20px;",
  "  padding: 0 var(--ust-s3);",
  "  border: 1px solid transparent;",
  "  border-radius: var(--ust-r-sm);",
  "  background: var(--ust-bg-inset);",
  "  color: var(--ust-text-2);",
  "  font-size: var(--ust-fs-micro);",
  "  font-weight: 600;",
  "  line-height: 1;",
  "  letter-spacing: 0.005em;",
  "  white-space: nowrap;",
  "  flex: none;",
  "}",
  ".uscistr-root .uscistr-chip svg { width: 11px; height: 11px; }",
  ".uscistr-root .uscistr-chip-dot { width: 6px; height: 6px; border-radius: var(--ust-r-full); background: currentColor; flex: none; }",
  ".uscistr-root .uscistr-chip-success { background: var(--ust-success-soft); border-color: var(--ust-success-border); color: var(--ust-success-text); }",
  ".uscistr-root .uscistr-chip-warn    { background: var(--ust-warn-soft);    border-color: var(--ust-warn-border);    color: var(--ust-warn-text); }",
  ".uscistr-root .uscistr-chip-danger  { background: var(--ust-danger-soft);  border-color: var(--ust-danger-border);  color: var(--ust-danger-text); }",
  ".uscistr-root .uscistr-chip-info    { background: var(--ust-info-soft);    border-color: var(--ust-info-border);    color: var(--ust-info-text); }",
  ".uscistr-root .uscistr-chip-accent  { background: var(--ust-accent-soft);  border-color: var(--ust-accent-soft-border); color: var(--ust-accent-soft-text); }",
  ".uscistr-root .uscistr-chip-neutral { background: var(--ust-bg-inset); border-color: var(--ust-border-1); color: var(--ust-text-2); }",
  ".uscistr-root .uscistr-chip-quiet   { background: transparent; border-color: var(--ust-border-2); color: var(--ust-text-3); }",
  ".uscistr-root .uscistr-chip-form {",
  "  font-family: var(--ust-mono);",
  "  font-size: 11px;",
  "  font-weight: 600;",
  "  letter-spacing: 0.02em;",
  "  font-variant-numeric: tabular-nums;",
  "  background: var(--ust-bg-inset);",
  "  border-color: var(--ust-border-1);",
  "  color: var(--ust-text-1);",
  "}",
  ".uscistr-root .uscistr-code {",
  "  display: inline-flex;",
  "  align-items: center;",
  "  height: 16px;",
  "  padding: 0 var(--ust-s2);",
  "  border: 1px solid var(--ust-border-1);",
  "  border-radius: var(--ust-r-xs);",
  "  background: var(--ust-bg-inset);",
  "  color: var(--ust-text-3);",
  "  font-family: var(--ust-mono);",
  "  font-size: 9.5px;",
  "  font-weight: 600;",
  "  letter-spacing: 0.04em;",
  "  line-height: 1;",
  "  flex: none;",
  "}",
  ".uscistr-root .uscistr-badge {",
  "  display: inline-flex;",
  "  align-items: center;",
  "  justify-content: center;",
  "  min-width: 16px;",
  "  height: 16px;",
  "  padding: 0 var(--ust-s2);",
  "  border-radius: var(--ust-r-full);",
  "  background: var(--ust-accent-solid);",
  "  color: var(--ust-accent-on);",
  "  font-family: var(--ust-mono);",
  "  font-size: 9.5px;",
  "  font-weight: 700;",
  "  font-variant-numeric: tabular-nums;",
  "  line-height: 1;",
  "}",
  ".uscistr-root .uscistr-banner {",
  "  display: grid;",
  "  grid-template-columns: auto 1fr auto;",
  "  align-items: start;",
  "  gap: var(--ust-s4);",
  "  margin: var(--ust-s5) var(--ust-s6) 0;",
  "  padding: var(--ust-s5);",
  "  border: 1px solid var(--ust-warn-border);",
  "  border-radius: var(--ust-r-lg);",
  "  background: var(--ust-warn-soft);",
  "  color: var(--ust-warn-text);",
  "}",
  ".uscistr-root .uscistr-banner svg { width: 15px; height: 15px; margin-top: 1px; flex: none; }",
  ".uscistr-root .uscistr-banner-body { display: flex; flex-direction: column; gap: var(--ust-s2); min-width: 0; }",
  ".uscistr-root .uscistr-banner-title { font-size: 12px; font-weight: 600; line-height: 1.35; }",
  ".uscistr-root .uscistr-banner-text { font-size: var(--ust-fs-meta); line-height: 1.45; color: var(--ust-warn-text); opacity: 0.92; }",
  ".uscistr-root .uscistr-banner-actions { display: flex; align-items: center; gap: var(--ust-s2); }",
  ".uscistr-root .uscistr-banner-danger { border-color: var(--ust-danger-border); background: var(--ust-danger-soft); color: var(--ust-danger-text); }",
  ".uscistr-root .uscistr-banner-danger .uscistr-banner-text { color: var(--ust-danger-text); }",
  ".uscistr-root .uscistr-banner-info { border-color: var(--ust-info-border); background: var(--ust-info-soft); color: var(--ust-info-text); }",
  ".uscistr-root .uscistr-banner-info .uscistr-banner-text { color: var(--ust-info-text); }",
  ".uscistr-root .uscistr-banner .uscistr-btn-sm {",
  "  border-color: currentColor;",
  "  color: inherit;",
  "  background: transparent;",
  "  box-shadow: none;",
  "  opacity: 0.95;",
  "}",
  ".uscistr-root .uscistr-banner .uscistr-btn-sm:hover { background: rgba(0, 0, 0, 0.06); }",
  ".uscistr-root.uscistr-dark .uscistr-banner .uscistr-btn-sm:hover { background: rgba(255, 255, 255, 0.08); }",
  ".uscistr-root .uscistr-case-list { display: block; }",
  ".uscistr-root .uscistr-collapsed {",
  "  display: flex; flex-direction: column; gap: 3px;",
  "  width: 100%; text-align: left; cursor: pointer;",
  "  background: none; border: 0; padding: var(--ust-s4) var(--ust-s5);",
  "  font: inherit; color: inherit; border-radius: var(--ust-r-md);",
  "}",
  ".uscistr-root .uscistr-collapsed:hover { background: var(--ust-bg-hover); }",
  ".uscistr-root .uscistr-collapsed-head { display: flex; align-items: center; gap: var(--ust-s3); min-width: 0; }",
  ".uscistr-root .uscistr-collapsed-dot {",
  "  width: 7px; height: 7px; flex: none; border-radius: var(--ust-r-full);",
  "  background: var(--ust-accent-solid);",
  "}",
  ".uscistr-root .uscistr-collapsed-name { font-weight: 600; font-size: var(--ust-fs-heading); min-width: 0; }",
  ".uscistr-root .uscistr-collapsed-body {",
  "  display: flex; align-items: baseline; gap: var(--ust-s3);",
  "  min-width: 0; padding-left: calc(7px + var(--ust-s3));",
  "}",
  ".uscistr-root .uscistr-collapsed-status { font-size: var(--ust-fs-meta); color: var(--ust-text-2); min-width: 0; flex: 1 1 auto; }",
  ".uscistr-root .uscistr-collapsed-age { font-size: var(--ust-fs-micro); color: var(--ust-text-3); flex: none; }",
    // Day N sits at the right of the identity line: a number that moves daily,
    // kept deliberately quiet so it never competes with the status.
    ".uscistr-root .uscistr-collapsed-day {",
    "  margin-left: auto; flex: none;",
    "  font-size: var(--ust-fs-micro); color: var(--ust-text-3);",
    "  font-variant-numeric: tabular-nums;",
    "}",
    // The only line on a collapsed row allowed to raise its voice, because it
    // is the only content that can be time-critical.
    ".uscistr-root .uscistr-collapsed-demand {",
    "  display: flex; align-items: center; gap: var(--ust-s3);",
    "  margin-top: 3px; padding-left: calc(7px + var(--ust-s3));",
    "  font-size: var(--ust-fs-micro); font-weight: 600;",
    "  color: var(--ust-warn-text);",
    "}",
    ".uscistr-root .uscistr-collapsed-demand-dot {",
    "  width: 5px; height: 5px; flex: none; border-radius: var(--ust-r-full);",
    "  background: var(--ust-warn);",
    "}",
  ".uscistr-root .uscistr-card.uscistr-is-collapsed { padding: 0; }",
  ".uscistr-root .uscistr-card {",
  "  position: relative;",
  "  display: flex;",
  "  flex-direction: column;",
  "  gap: var(--ust-s5);",
  "  padding: var(--ust-s6) var(--ust-s6) var(--ust-s6) var(--ust-s6);",
  "  box-shadow: inset 0 -1px 0 var(--ust-border-1);",
  "  transition: background-color var(--ust-d2) var(--ust-ease);",
  "}",
  ".uscistr-root .uscistr-card:last-child { box-shadow: none; }",
  ".uscistr-root .uscistr-card::before {",
  "  content: \"\";",
  "  position: absolute;",
  "  left: 0;",
  "  top: var(--ust-s6);",
  "  bottom: var(--ust-s6);",
  "  width: 2px;",
  "  border-radius: 0 var(--ust-r-full) var(--ust-r-full) 0;",
  "  background: transparent;",
  "  transition: background-color var(--ust-d2) var(--ust-ease);",
  "}",
  ".uscistr-root .uscistr-card.uscistr-is-changed { background: var(--ust-tint-accent); }",
  ".uscistr-root .uscistr-card.uscistr-is-changed::before { background: var(--ust-accent-solid); }",
  ".uscistr-root .uscistr-card.uscistr-is-attention::before { background: var(--ust-warn); }",
  ".uscistr-root .uscistr-card.uscistr-is-error::before { background: var(--ust-danger); }",
  ".uscistr-root .uscistr-card.uscistr-is-closed .uscistr-card-label { color: var(--ust-text-2); }",
  ".uscistr-root .uscistr-card-header {",
  "  display: grid;",
  "  grid-template-columns: 1fr auto;",
  "  align-items: start;",
  "  gap: var(--ust-s4);",
  "}",
  ".uscistr-root .uscistr-card-title { display: flex; flex-direction: column; gap: var(--ust-s2); min-width: 0; }",
  ".uscistr-root .uscistr-card-eyebrow { display: flex; align-items: center; flex-wrap: wrap; gap: var(--ust-s3) var(--ust-s3); min-width: 0; }",
  ".uscistr-root .uscistr-card-label {",
  "  font-size: var(--ust-fs-heading);",
  "  line-height: var(--ust-lh-heading);",
  "  font-weight: 600;",
  "  letter-spacing: -0.008em;",
  "  color: var(--ust-text-1);",
  "  overflow: hidden;",
  "  text-overflow: ellipsis;",
  "  display: -webkit-box;",
  "  -webkit-line-clamp: 2;",
  "  -webkit-box-orient: vertical;",
  "}",
  ".uscistr-root .uscistr-card-actions { display: flex; align-items: center; gap: var(--ust-s1); flex: none; }",
  ".uscistr-root .uscistr-receipt {",
  "  display: inline-flex;",
  "  align-items: center;",
  "  gap: var(--ust-s3);",
  "  align-self: flex-start;",
  "  max-width: 100%;",
  "  height: 22px;",
  "  margin-left: -4px;",
  "  padding: 0 var(--ust-s2);",
  "  border: 1px solid transparent;",
  "  border-radius: var(--ust-r-sm);",
  "  background: transparent;",
  "  color: var(--ust-text-2);",
  "  font-family: var(--ust-mono);",
  "  font-size: var(--ust-fs-mono);",
  "  font-weight: 500;",
  "  letter-spacing: 0.035em;",
  "  font-variant-numeric: tabular-nums;",
  "  line-height: 1;",
  "  cursor: pointer;",
  "  transition: background-color var(--ust-d1) var(--ust-ease), color var(--ust-d1) var(--ust-ease), border-color var(--ust-d1) var(--ust-ease);",
  "}",
  ".uscistr-root .uscistr-receipt svg { width: 12px; height: 12px; opacity: 0; transition: opacity var(--ust-d1) var(--ust-ease); }",
  ".uscistr-root .uscistr-receipt:hover { background: var(--ust-bg-inset); border-color: var(--ust-border-1); color: var(--ust-text-1); }",
  ".uscistr-root .uscistr-receipt:hover svg { opacity: 1; }",
  ".uscistr-root .uscistr-receipt.uscistr-is-redacted { letter-spacing: 0.08em; }",
  ".uscistr-root .uscistr-card-footer {",
  "  display: flex;",
  "  align-items: center;",
  "  gap: var(--ust-s2);",
  "  flex-wrap: wrap;",
  "  padding-top: var(--ust-s1);",
  "}",
  ".uscistr-root .uscistr-card-footer .uscistr-btn-danger { margin-left: auto; }",
  ".uscistr-root .uscistr-status-block { display: flex; flex-direction: column; gap: var(--ust-s3); }",
  ".uscistr-root .uscistr-status-row { display: flex; align-items: center; gap: var(--ust-s3); flex-wrap: wrap; }",
  ".uscistr-root .uscistr-status-text {",
  // Serif, and the largest thing on the card. USCIS's own sentence about
  // this person's case is the reason the panel exists; setting it in the
  // same sans as the chrome buried it under a static form title.
  "  font-family: var(--ust-serif);",
  "  font-size: 17px;",
  "  line-height: 1.3;",
  "  font-weight: 600;",
  "  letter-spacing: -0.004em;",
  "  color: var(--ust-text-1);",
  "  text-wrap: balance;",
  "}",
  ".uscistr-root .uscistr-status-desc {",
  "  font-size: var(--ust-fs-body);",
  "  line-height: var(--ust-lh-body);",
  "  color: var(--ust-text-2);",
  "}",
  ".uscistr-root .uscistr-status-desc.uscistr-is-clamped {",
  "  display: -webkit-box;",
  "  -webkit-line-clamp: 3;",
  "  -webkit-box-orient: vertical;",
  "  overflow: hidden;",
  "}",
  ".uscistr-root .uscistr-more {",
  "  align-self: flex-start;",
  "  border: 0;",
  "  background: none;",
  "  color: var(--ust-accent);",
  "  font-size: var(--ust-fs-meta);",
  "  font-weight: 560;",
  "  line-height: 1.2;",
  "  cursor: pointer;",
  "  border-radius: var(--ust-r-xs);",
  "}",
  ".uscistr-root .uscistr-more:hover { text-decoration: underline; text-underline-offset: 2px; }",
  ".uscistr-root .uscistr-change {",
  "  display: grid;",
  "  grid-template-columns: auto 1fr auto;",
  "  align-items: center;",
  "  gap: var(--ust-s3);",
  "  padding: var(--ust-s3) var(--ust-s4);",
  "  border: 1px solid var(--ust-accent-soft-border);",
  "  border-radius: var(--ust-r-md);",
  "  background: var(--ust-accent-soft);",
  "  color: var(--ust-accent-soft-text);",
  "  font-size: var(--ust-fs-meta);",
  "  line-height: 1.4;",
  "  font-weight: 500;",
  "}",
  ".uscistr-root .uscistr-change svg { width: 13px; height: 13px; flex: none; }",
  ".uscistr-root .uscistr-change b { font-weight: 650; }",
  ".uscistr-root .uscistr-fields {",
  "  display: grid;",
  "  grid-template-columns: max-content minmax(0, 1fr);",
  "  column-gap: var(--ust-s6);",
  "  row-gap: var(--ust-s3);",
  "  align-items: baseline;",
  "}",
  ".uscistr-root .uscistr-field-label {",
  "  font-size: var(--ust-fs-meta);",
  "  line-height: var(--ust-lh-meta);",
  "  font-weight: 500;",
  "  color: var(--ust-text-3);",
  "  white-space: nowrap;",
  "}",
  ".uscistr-root .uscistr-field-value {",
  "  display: flex;",
  "  align-items: baseline;",
  "  flex-wrap: wrap;",
  "  gap: var(--ust-s3);",
  "  font-size: var(--ust-fs-meta);",
  "  line-height: var(--ust-lh-meta);",
  "  color: var(--ust-text-1);",
  "  font-variant-numeric: tabular-nums;",
  "  min-width: 0;",
  "}",
  ".uscistr-root .uscistr-rel { color: var(--ust-text-3); }",
  ".uscistr-root .uscistr-progress { display: flex; flex-direction: column; gap: var(--ust-s3); }",
  ".uscistr-root .uscistr-progress-head {",
  "  display: flex;",
  "  align-items: baseline;",
  "  justify-content: space-between;",
  "  gap: var(--ust-s4);",
  "  font-size: var(--ust-fs-meta);",
  "  line-height: 1.3;",
  "}",
  ".uscistr-root .uscistr-progress-head b { font-weight: 600; color: var(--ust-text-1); }",
  ".uscistr-root .uscistr-progress-track {",
  "  position: relative;",
  "  height: 6px;",
  "  border-radius: var(--ust-r-full);",
  "  background: var(--ust-track);",
  "  overflow: hidden;",
  "}",
  ".uscistr-root .uscistr-progress-fill {",
  "  height: 100%;",
  "  border-radius: var(--ust-r-full);",
  "  background: var(--ust-accent-solid);",
  "  transition: width var(--ust-d4) var(--ust-ease-out);",
  "}",
  "  background: repeating-linear-gradient(115deg,",
  "    var(--ust-accent-solid) 0 8px,",
  "    color-mix(in srgb, var(--ust-accent-solid) 55%, transparent) 8px 16px);",
  "  background-size: 200% 100%;",
  "  animation: ust-drift 1.6s linear infinite;",
  "}",
  ".uscistr-root .uscistr-progress-label { font-size: var(--ust-fs-micro); line-height: 1.4; color: var(--ust-text-3); }",
  ".uscistr-root .uscistr-section { display: flex; flex-direction: column; gap: var(--ust-s4); }",
  ".uscistr-root .uscistr-section-title {",
  "  display: flex;",
  "  align-items: center;",
  "  gap: var(--ust-s3);",
  "  font-size: var(--ust-fs-label);",
  "  line-height: var(--ust-lh-label);",
  "  font-weight: 600;",
  "  text-transform: uppercase;",
  "  letter-spacing: 0.075em;",
  "  color: var(--ust-text-3);",
  "}",
  ".uscistr-root .uscistr-section-title::after {",
  "  content: \"\";",
  "  flex: 1 1 auto;",
  "  height: 1px;",
  "  background: var(--ust-border-1);",
  "}",
  ".uscistr-root .uscistr-note {",
  "  padding: var(--ust-s4) var(--ust-s5);",
  "  border: 1px dashed var(--ust-border-2);",
  "  border-radius: var(--ust-r-md);",
  "  background: var(--ust-bg-sunken);",
  "  color: var(--ust-text-3);",
  "  font-size: var(--ust-fs-meta);",
  "  line-height: 1.5;",
  "}",
  ".uscistr-root .uscistr-timeline { position: relative; display: flex; flex-direction: column; padding-left: 14px; }",
  ".uscistr-root .uscistr-timeline::before {",
  "  content: \"\";",
  "  position: absolute;",
  "  left: 3px;",
  "  top: 10px;",
  "  bottom: 10px;",
  "  width: 1px;",
  "  background: var(--ust-border-2);",
  "}",
  ".uscistr-root .uscistr-timeline-row {",
  "  position: relative;",
  "  display: grid;",
  "  grid-template-columns: 58px minmax(0, 1fr);",
  "  column-gap: var(--ust-s4);",
  "  padding: var(--ust-s3) 0;",
  "}",
  ".uscistr-root .uscistr-timeline-row::before {",
  "  content: \"\";",
  "  position: absolute;",
  "  left: -14px;",
  "  top: 11px;",
  "  width: 7px;",
  "  height: 7px;",
  "  border-radius: var(--ust-r-full);",
  "  background: var(--ust-border-field);",
  "  box-shadow: 0 0 0 3px var(--ust-bg-panel);",
  "}",
  ".uscistr-root .uscistr-card.uscistr-is-changed .uscistr-timeline-row::before { box-shadow: none; }",
  ".uscistr-root .uscistr-timeline-row.uscistr-is-current::before {",
  "  background: var(--ust-accent-solid);",
  "  box-shadow: 0 0 0 3px var(--ust-bg-panel), 0 0 0 5px var(--ust-accent-soft);",
  "}",
  ".uscistr-root .uscistr-timeline-date {",
  "  font-family: var(--ust-mono);",
  "  font-size: 10.5px;",
  "  line-height: 1.5;",
  "  font-variant-numeric: tabular-nums;",
  "  letter-spacing: 0.01em;",
  "  color: var(--ust-text-3);",
  "  white-space: nowrap;",
  "  padding-top: 1px;",
  "}",
  ".uscistr-root .uscistr-timeline-body { display: flex; flex-direction: column; gap: var(--ust-s2); min-width: 0; }",
  ".uscistr-root .uscistr-timeline-text {",
  "  font-size: var(--ust-fs-meta);",
  "  line-height: 1.5;",
  "  color: var(--ust-text-1);",
  "}",
  ".uscistr-root .uscistr-timeline-row.uscistr-is-current .uscistr-timeline-text { font-weight: 560; }",
  ".uscistr-root .uscistr-timeline-meta { display: flex; align-items: center; gap: var(--ust-s3); flex-wrap: wrap; }",
  "  font-size: var(--ust-fs-micro);",
  "  line-height: 1.4;",
  "  color: var(--ust-text-3);",
  "}",
  "  content: \"unofficial\";",
  "  display: inline-block;",
  "  margin-left: var(--ust-s3);",
  "  padding: 0 4px;",
  "  border: 1px solid var(--ust-border-1);",
  "  border-radius: var(--ust-r-xs);",
  "  font-size: 9px;",
  "  letter-spacing: 0.04em;",
  "  text-transform: uppercase;",
  "  color: var(--ust-text-3);",
  "  vertical-align: 1px;",
  "}",
  ".uscistr-root .uscistr-documents { display: flex; flex-direction: column; gap: var(--ust-s1); }",
  ".uscistr-root .uscistr-doc-row {",
  "  display: grid;",
  "  grid-template-columns: 16px minmax(0, 1fr) auto;",
  "  align-items: center;",
  "  gap: var(--ust-s4);",
  "  padding: var(--ust-s3) var(--ust-s4);",
  "  margin: 0 calc(var(--ust-s4) * -1);",
  "  border-radius: var(--ust-r-md);",
  "  transition: background-color var(--ust-d1) var(--ust-ease);",
  "}",
  ".uscistr-root .uscistr-doc-row:hover { background: var(--ust-bg-hover); }",
  ".uscistr-root .uscistr-doc-row svg { width: 14px; height: 14px; color: var(--ust-text-3); }",
  ".uscistr-root .uscistr-doc-main { display: flex; align-items: baseline; gap: var(--ust-s3); min-width: 0; font-size: var(--ust-fs-meta); line-height: var(--ust-lh-meta); color: var(--ust-text-1); }",
  ".uscistr-root .uscistr-doc-main > span:first-child { flex: 0 0 auto; white-space: nowrap; }",
  ".uscistr-root .uscistr-doc-name { flex: 0 1 auto; color: var(--ust-text-3); }",
  ".uscistr-root .uscistr-doc-name {",
  "  font-family: var(--ust-mono);",
  "  font-size: 11px;",
  "  line-height: 1.4;",
  "  color: var(--ust-text-1);",
  "  white-space: nowrap;",
  "  overflow: hidden;",
  "  text-overflow: ellipsis;",
  "  direction: ltr;",
  "}",
  ".uscistr-root .uscistr-doc-date {",
  "  font-size: var(--ust-fs-micro);",
  "  line-height: 1.4;",
  "  color: var(--ust-text-3);",
  "  font-variant-numeric: tabular-nums;",
  "  white-space: nowrap;",
  "}",
  ".uscistr-root .uscistr-raw-wrap { display: flex; flex-direction: column; gap: var(--ust-s3); }",
  ".uscistr-root .uscistr-raw-summary {",
  "  display: grid;",
  "  grid-template-columns: 12px minmax(0, 1fr) auto;",
  "  align-items: center;",
  "  gap: var(--ust-s3);",
  "  width: calc(100% + var(--ust-s4) * 2);",
  "  height: 26px;",
  "  padding: 0 var(--ust-s4);",
  "  margin: 0 calc(var(--ust-s4) * -1);",
  "  border-radius: var(--ust-r-sm);",
  "  background: transparent;",
  "  color: var(--ust-text-3);",
  "  font-family: var(--ust-mono);",
  "  font-size: 10.5px;",
  "  letter-spacing: 0.01em;",
  "  cursor: pointer;",
  "  transition: background-color var(--ust-d1) var(--ust-ease), color var(--ust-d1) var(--ust-ease);",
  "}",
  ".uscistr-root .uscistr-raw-summary:hover { background: var(--ust-bg-hover); color: var(--ust-text-1); }",
  ".uscistr-root .uscistr-raw-summary svg {",
  "  width: 12px;",
  "  height: 12px;",
  "  transition: transform var(--ust-d2) var(--ust-ease);",
  "}",
  ".uscistr-root .uscistr-raw-summary[aria-expanded=\"true\"] svg { transform: rotate(90deg); }",
  ".uscistr-root .uscistr-raw-summary[aria-expanded=\"true\"] { color: var(--ust-text-1); }",
  ".uscistr-root .uscistr-raw-path { text-align: left; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
  ".uscistr-root .uscistr-raw {",
  "  max-height: 200px;",
  "  padding: var(--ust-s5);",
  "  border: 1px solid var(--ust-border-1);",
  "  border-radius: var(--ust-r-md);",
  "  background: var(--ust-bg-inset);",
  "  color: var(--ust-text-2);",
  "  font-family: var(--ust-mono);",
  "  font-size: 10.5px;",
  "  line-height: 1.55;",
  "  white-space: pre;",
  "  overflow: auto;",
  "  overscroll-behavior: contain;",
  "  scrollbar-width: thin;",
  "  scrollbar-color: var(--ust-scroll-thumb) transparent;",
  "  -webkit-user-select: text;",
  "  user-select: text;",
  "}",
  ".uscistr-root .uscistr-raw::-webkit-scrollbar { width: 10px; height: 10px; }",
  ".uscistr-root .uscistr-raw::-webkit-scrollbar-thumb {",
  "  background-color: var(--ust-scroll-thumb);",
  "  border: 3px solid transparent;",
  "  background-clip: padding-box;",
  "  border-radius: var(--ust-r-full);",
  "}",
  ".uscistr-root .uscistr-raw[hidden] { display: none; }",
  ".uscistr-root .uscistr-empty {",
  "  display: flex;",
  "  flex-direction: column;",
  "  align-items: center;",
  "  text-align: center;",
  "  gap: var(--ust-s4);",
  "  padding: var(--ust-s10) var(--ust-s8);",
  "}",
  ".uscistr-root .uscistr-empty-icon {",
  "  display: flex;",
  "  align-items: center;",
  "  justify-content: center;",
  "  width: 40px;",
  "  height: 40px;",
  "  border-radius: var(--ust-r-full);",
  "  background: var(--ust-bg-inset);",
  "  color: var(--ust-text-3);",
  "  margin-bottom: var(--ust-s1);",
  "}",
  ".uscistr-root .uscistr-empty-icon svg { width: 18px; height: 18px; }",
  ".uscistr-root .uscistr-empty-title { font-size: 13px; line-height: 1.35; font-weight: 600; color: var(--ust-text-1); }",
  ".uscistr-root .uscistr-empty-text { font-size: var(--ust-fs-body); line-height: 1.55; color: var(--ust-text-3); max-width: 30ch; }",
  ".uscistr-root .uscistr-empty .uscistr-btn { margin-top: var(--ust-s2); }",
  ".uscistr-root .uscistr-popover {",
  "  position: absolute;",
  "  top: 42px;",
  "  right: var(--ust-s5);",
  "  z-index: 6;",
  "  width: 262px;",
  "  padding: var(--ust-s3);",
  "  border: 1px solid var(--ust-border-2);",
  "  border-radius: var(--ust-r-lg);",
  "  background: var(--ust-bg-raised-solid);",
  "  box-shadow: var(--ust-sh-pop), var(--ust-sh-inner);",
  "  animation: ust-pop-in var(--ust-d3) var(--ust-ease-out) both;",
  "  transform-origin: top right;",
  "}",
  ".uscistr-root .uscistr-popover-head {",
  "  padding: var(--ust-s2) var(--ust-s4) var(--ust-s4);",
  "  font-size: var(--ust-fs-label);",
  "  font-weight: 600;",
  "  text-transform: uppercase;",
  "  letter-spacing: 0.075em;",
  "  color: var(--ust-text-3);",
  "}",
  ".uscistr-root .uscistr-popover-row {",
  "  display: grid;",
  "  grid-template-columns: minmax(0, 1fr) auto;",
  "  align-items: center;",
  "  gap: var(--ust-s5);",
  "  padding: var(--ust-s4);",
  "  border-radius: var(--ust-r-md);",
  "  transition: background-color var(--ust-d1) var(--ust-ease);",
  "}",
  ".uscistr-root .uscistr-popover-row:hover { background: var(--ust-bg-hover); }",
  ".uscistr-root .uscistr-popover-label { font-size: 12.5px; line-height: 1.3; font-weight: 500; color: var(--ust-text-1); }",
  ".uscistr-root .uscistr-popover-desc { font-size: var(--ust-fs-micro); line-height: 1.4; color: var(--ust-text-3); margin-top: 2px; }",
  ".uscistr-root .uscistr-popover-sep { height: 1px; margin: var(--ust-s2) var(--ust-s4); background: var(--ust-border-1); }",
  ".uscistr-root .uscistr-popover .uscistr-select { width: 104px; height: 26px; line-height: 24px; font-size: 11.5px; }",
  ".uscistr-root .uscistr-mono { font-family: var(--ust-mono); font-variant-numeric: tabular-nums; }",
  ".uscistr-root .uscistr-muted { color: var(--ust-text-3); }",
  ".uscistr-root .uscistr-small { font-size: var(--ust-fs-meta); line-height: var(--ust-lh-meta); }",
  ".uscistr-root .uscistr-truncate { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; min-width: 0; }",
  ".uscistr-root .uscistr-error { color: var(--ust-danger-text); font-size: var(--ust-fs-meta); line-height: 1.45; }",
  ".uscistr-root .uscistr-link { color: var(--ust-accent); text-decoration: underline; text-underline-offset: 2px; cursor: pointer; border-radius: var(--ust-r-xs); }",
  "  position: absolute !important;",
  "  width: 1px; height: 1px;",
  "  padding: 0; margin: -1px;",
  "  overflow: hidden;",
  "  clip: rect(0 0 0 0);",
  "  clip-path: inset(50%);",
  "  white-space: nowrap;",
  "  border: 0;",
  "}",
  ".uscistr-root .uscistr-skeleton {",
  "  border-radius: var(--ust-r-xs);",
  "  background: linear-gradient(90deg, var(--ust-bg-inset) 25%, var(--ust-bg-hover) 37%, var(--ust-bg-inset) 63%);",
  "  background-size: 400% 100%;",
  "  animation: ust-shimmer 1.4s ease-in-out infinite;",
  "  color: transparent;",
  "}",
  ".uscistr-root .uscistr-hidden-file { display: none; }",
  ".uscistr-root .uscistr-btn-small { height: 24px; padding: 0 var(--ust-s4); font-size: 11.5px; border-radius: var(--ust-r-sm); }",
  ".uscistr-root .uscistr-btn-small svg { width: 12px; height: 12px; }",
  ".uscistr-root .uscistr-card-number {",
  "  font-family: var(--ust-mono);",
  "  font-size: var(--ust-fs-mono);",
  "  letter-spacing: 0.035em;",
  "  font-variant-numeric: tabular-nums;",
  "  color: var(--ust-text-2);",
  "}",
  ".uscistr-root .uscistr-tag {",
  "  display: inline-flex;",
  "  align-items: center;",
  "  height: 16px;",
  "  padding: 0 var(--ust-s2);",
  "  border: 1px solid var(--ust-border-1);",
  "  border-radius: var(--ust-r-xs);",
  "  background: var(--ust-bg-inset);",
  "  color: var(--ust-text-3);",
  "  font-family: var(--ust-mono);",
  "  font-size: 9.5px;",
  "  font-weight: 600;",
  "  letter-spacing: 0.04em;",
  "  line-height: 1;",
  "  flex: none;",
  "}",
  ".uscistr-root .uscistr-checkbox-row {",
  "  display: grid;",
  "  grid-template-columns: minmax(0, 1fr) auto;",
  "  align-items: center;",
  "  gap: var(--ust-s5);",
  "  padding: var(--ust-s4);",
  "  border-radius: var(--ust-r-md);",
  "  font-size: 12.5px;",
  "}",
  ".uscistr-root .uscistr-checkbox-row:hover { background: var(--ust-bg-hover); }",
  ".uscistr-root .uscistr-version { font-size: 10.5px; color: var(--ust-text-3); font-variant-numeric: tabular-nums; }",
  "@keyframes ust-panel-in {",
  "  from { opacity: 0; transform: translateY(8px) scale(0.985); }",
  "  to   { opacity: 1; transform: none; }",
  "}",
  "@keyframes ust-pop-in {",
  "  from { opacity: 0; transform: translateY(-4px) scale(0.97); }",
  "  to   { opacity: 1; transform: none; }",
  "}",
  "@keyframes ust-spin { to { transform: rotate(360deg); } }",
  "@keyframes ust-ping {",
  "  0%   { opacity: 0.7; transform: scale(0.8); }",
  "  70%  { opacity: 0;   transform: scale(1.9); }",
  "  100% { opacity: 0;   transform: scale(1.9); }",
  "}",
  "@keyframes ust-shimmer { from { background-position: 100% 0; } to { background-position: 0 0; } }",
  "@keyframes ust-drift { to { background-position: -200% 0; } }",
  "@media (prefers-reduced-motion: reduce) {",
  "  .uscistr-root,",
  "  .uscistr-root *,",
  "  .uscistr-root *::before,",
  "  .uscistr-root *::after {",
  "    animation-duration: 1ms !important;",
  "    animation-iteration-count: 1 !important;",
  "    transition-duration: 1ms !important;",
  "    scroll-behavior: auto !important;",
  "  }",
  "  .uscistr-root .uscistr-pill:hover { transform: none; }",
  "  .uscistr-root .uscistr-btn:active { transform: none; }",
  "}",
  ".uscistr-root .uscistr-ico .uscistr-fill { fill: currentColor; stroke: none; }",
  ".uscistr-root .uscistr-ico .uscistr-faint { opacity: 0.4; }",
  ".uscistr-root .uscistr-ico .uscistr-thin { stroke-width: 1; }",
  ".uscistr-root .uscistr-ico .uscistr-hair { stroke-width: 1.3; }",
  ".uscistr-root .uscistr-timeline { padding-left: 0; }",
  ".uscistr-root .uscistr-timeline::before { display: none; }",
  ".uscistr-root .uscistr-timeline-row {",
  "  display: grid;",
  "  grid-template-columns: 18px minmax(0, 1fr);",
  "  column-gap: var(--ust-s4);",
  "  padding: 0;",
  "}",
  ".uscistr-root .uscistr-timeline-row::before { display: none; }",
  ".uscistr-root .uscistr-node {",
  "  position: relative;",
  "  display: flex;",
  "  justify-content: center;",
  "  color: var(--ust-text-3);",
  "}",
  ".uscistr-root .uscistr-node svg { width: 12px; height: 12px; margin-top: 7px; }",
  ".uscistr-root .uscistr-node::after {",
  "  content: \"\";",
  "  position: absolute;",
  "  left: 50%;",
  "  top: 22px;",
  "  bottom: -2px;",
  "  width: 1px;",
  "  margin-left: -0.5px;",
  "  background: var(--ust-border-2);",
  "}",
  ".uscistr-root .uscistr-node-last::after { display: none; }",
  ".uscistr-root .uscistr-node-through::after { top: 0; }",
  ".uscistr-root .uscistr-node-official { color: var(--ust-accent); }",
  ".uscistr-root .uscistr-node-coded { color: var(--ust-accent); }",
  ".uscistr-root .uscistr-node-quiet { color: var(--ust-text-3); }",
  ".uscistr-root .uscistr-node-local { color: var(--ust-warn); }",
  ".uscistr-root .uscistr-node-attention { color: var(--ust-danger); }",
  ".uscistr-root .uscistr-timeline-cell { min-width: 0; padding: var(--ust-s3) 0; }",
  ".uscistr-root .uscistr-row-toggle {",
  "  display: block;",
  "  width: 100%;",
  "  text-align: left;",
  "  border-radius: var(--ust-r-sm);",
  "  cursor: pointer;",
  "  background: transparent;",
  "}",
  ".uscistr-root .uscistr-row-toggle:hover { background: var(--ust-bg-hover); }",
  ".uscistr-root .uscistr-timeline-head {",
  "  display: flex;",
  "  align-items: baseline;",
  "  justify-content: space-between;",
  "  gap: var(--ust-s3);",
  "}",
  ".uscistr-root .uscistr-timeline-text.uscistr-is-quiet { color: var(--ust-text-3); }",
  ".uscistr-root .uscistr-timeline-text.uscistr-is-attention { font-weight: 600; }",
  ".uscistr-root .uscistr-unofficial-label { text-decoration: underline dotted; text-underline-offset: 3px; }",
  ".uscistr-root .uscistr-timeline-sub {",
  "  font-family: var(--ust-mono);",
  "  font-size: 10.5px;",
  "  line-height: 1.4;",
  "  color: var(--ust-text-3);",
  "  overflow: hidden;",
  "  text-overflow: ellipsis;",
  "  white-space: nowrap;",
  "}",
  ".uscistr-root .uscistr-disclosure {",
  "  margin-top: var(--ust-s3);",
  "  padding: var(--ust-s4);",
  "  border-radius: var(--ust-r-sm);",
  "  background: var(--ust-bg-sunken);",
  "  color: var(--ust-text-2);",
  "  font-size: var(--ust-fs-meta);",
  "  line-height: 1.55;",
  "}",
  ".uscistr-root .uscistr-disclosure p { margin-top: var(--ust-s3); }",
  ".uscistr-root .uscistr-disclosure p:first-child { margin-top: 0; }",
  ".uscistr-root .uscistr-gap {",
  "  display: grid;",
  "  grid-template-columns: 18px minmax(0, 1fr);",
  "  column-gap: var(--ust-s4);",
  "}",
  ".uscistr-root .uscistr-gap-text {",
  "  padding: var(--ust-s2) 0;",
  "  font-size: var(--ust-fs-micro);",
  "  line-height: 1.4;",
  "  color: var(--ust-text-3);",
  "  font-variant-numeric: tabular-nums;",
  "}",
  ".uscistr-root .uscistr-timeline-fold { margin-top: var(--ust-s3); align-self: flex-start; }",
  ".uscistr-root .uscistr-stage { display: flex; align-items: flex-start; }",
  ".uscistr-root .uscistr-stage-seg {",
  "  position: relative;",
  "  flex: 1 1 0;",
  "  min-width: 0;",
  "  display: flex;",
  "  flex-direction: column;",
  "  align-items: center;",
  "  gap: var(--ust-s2);",
  "}",
  ".uscistr-root .uscistr-stage-seg::after {",
  "  content: \"\";",
  "  position: absolute;",
  "  top: 5px;",
  "  left: calc(50% + 9px);",
  "  right: calc(-50% + 9px);",
  "  height: 2px;",
  "  border-radius: var(--ust-r-full);",
  "  background: var(--ust-border-2);",
  "}",
  ".uscistr-root .uscistr-stage-seg:last-child::after { display: none; }",
  ".uscistr-root .uscistr-stage-seg.uscistr-is-done::after { background: var(--ust-accent-solid); }",
  ".uscistr-root .uscistr-stage-seg.uscistr-is-ahead::after {",
  "  height: 0;",
  "  background: transparent;",
  "  border-top: 2px dotted var(--ust-border-field);",
  "}",
  ".uscistr-root .uscistr-stage-node { display: flex; align-items: center; justify-content: center; height: 12px; color: var(--ust-border-field); }",
  ".uscistr-root .uscistr-stage-node svg { width: 11px; height: 11px; }",
  ".uscistr-root .uscistr-stage-seg.uscistr-is-done .uscistr-stage-node,",
  ".uscistr-root .uscistr-stage-seg.uscistr-is-current .uscistr-stage-node { color: var(--ust-accent); }",
  ".uscistr-root .uscistr-stage-label {",
  "  font-size: 9.5px;",
  "  line-height: 1.25;",
  "  text-align: center;",
  "  color: var(--ust-text-3);",
  "  letter-spacing: 0.01em;",
  "  overflow: hidden;",
  "  text-overflow: ellipsis;",
  "  max-width: 100%;",
  "}",
  ".uscistr-root .uscistr-stage-seg.uscistr-is-done .uscistr-stage-label { color: var(--ust-text-2); }",
  ".uscistr-root .uscistr-stage-seg.uscistr-is-current .uscistr-stage-label { color: var(--ust-text-1); font-weight: 600; }",
  ".uscistr-root .uscistr-stage-here { font-size: 9px; line-height: 1.2; color: var(--ust-accent); white-space: nowrap; }",
  ".uscistr-root .uscistr-quiet { display: flex; flex-direction: column; gap: var(--ust-s2); }",
  ".uscistr-root .uscistr-quiet-head {",
  "  display: flex;",
  "  align-items: baseline;",
  "  justify-content: space-between;",
  "  gap: var(--ust-s4);",
  "  font-size: var(--ust-fs-meta);",
  "  line-height: 1.3;",
  "  color: var(--ust-text-2);",
  "  font-variant-numeric: tabular-nums;",
  "}",
  ".uscistr-root .uscistr-upcoming {",
  "  display: grid;",
  "  grid-template-columns: auto minmax(0, 1fr) auto;",
  "  align-items: center;",
  "  gap: var(--ust-s4);",
  "  padding: var(--ust-s4) var(--ust-s5);",
  "  border: 1px solid var(--ust-accent-soft-border);",
  "  border-radius: var(--ust-r-md);",
  "  background: var(--ust-tint-accent);",
  "}",
  ".uscistr-root .uscistr-upcoming svg { width: 14px; height: 14px; color: var(--ust-accent); }",
  ".uscistr-root .uscistr-upcoming-title { font-size: var(--ust-fs-meta); font-weight: 600; color: var(--ust-text-1); }",
  ".uscistr-root .uscistr-upcoming-meta { font-size: var(--ust-fs-micro); color: var(--ust-text-3); }",
  ".uscistr-root .uscistr-section-count { font-weight: 500; letter-spacing: 0.02em; }",
  ".uscistr-root .uscistr-doc-meta { display: flex; align-items: center; gap: var(--ust-s3); }",
  ".uscistr-root .uscistr-add-error { grid-column: 1 / -1; display: flex; align-items: baseline; gap: var(--ust-s4); }",
  ".uscistr-root .uscistr-add-error .uscistr-field-error { min-width: 0; }",
  ".uscistr-root .uscistr-stack { display: flex; flex-direction: column; gap: var(--ust-s3); }",
  ".uscistr-root .uscistr-skeleton-row { display: grid; grid-template-columns: 12px minmax(0, 1fr); column-gap: var(--ust-s4); align-items: center; }",
  ".uscistr-root .uscistr-skeleton-dot { width: 12px; height: 12px; border-radius: var(--ust-r-full); }",
  ".uscistr-root .uscistr-skeleton-bar { height: 9px; }",
  ".uscistr-root .uscistr-note-title { font-weight: 600; color: var(--ust-text-2); }",
  ".uscistr-root .uscistr-note p { margin-top: var(--ust-s2); }",
  ".uscistr-root .uscistr-note p:first-child { margin-top: 0; }",
  ".uscistr-root .uscistr-standing {",
  "  padding: var(--ust-s5) var(--ust-s6);",
  "  font-size: var(--ust-fs-micro);",
  "  line-height: 1.5;",
  "  color: var(--ust-text-3);",
  "  box-shadow: inset 0 1px 0 var(--ust-border-1);",
  "}",
  ".uscistr-root .uscistr-footer .uscistr-btn-sm { color: var(--ust-text-3); }",
  ".uscistr-root .uscistr-footer .uscistr-btn-sm:hover { color: var(--ust-text-1); background: var(--ust-bg-hover); }",
  ".uscistr-root .uscistr-timeline-meta { font-size: var(--ust-fs-micro); line-height: 1.4; color: var(--ust-text-3); }",
  ".uscistr-root .uscistr-timeline-note { font-size: var(--ust-fs-micro); line-height: 1.45; color: var(--ust-text-3); }",
  ".uscistr-root .uscistr-code-copy { align-self: flex-start; margin-top: var(--ust-s2); }"
].join('\n');
